name: Blog build & deploy

on:
  push:
    branches: [ "master" ]
env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3
        with:
          ref: "master"
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "16.20.2"
      
      - name: Cache node modules
        uses: actions/cache@v1.2.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      
      - name: Files generate
        run: |
          npm install
          npm run build
          echo "freezing.cool" > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-page
          build_dir: ./dist
          jekyll: false
