name: Blog build & deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3
        with:
          ref: "master"
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.20.2"
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      
      - name: Files generate
        run: |
          npm install
          npm run build
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    
    steps:  
      - name: Deploy to gh-page
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          git-config-name: blleng
          git-config-email: l0bl@outlook.com
          branch: gh-page
          folder: ./dist
